
name: Merge

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install tox and coverage
      run: pip install tox coverage

    # Runs Python tests
    - name: Run Python tests
      run: make py39-tests

    # Uploads the coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        name: coverage
        fail_ci_if_error: true
