
name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    # Install dependencies
    - name: Install tox and coverage
      run: pip install tox coverage

    # Runs Python tests
    - name: Run Python tests
      run: make py37-tests

    # Uploads the coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        name: coverage
        fail_ci_if_error: true

    # Docs tests
    - name: Install docs dependecies
      run: pip install -r docs/requirements.txt

    - name: Run Docs tests
      run: make docs
